import type { DragonAchievement } from './achievement-models';

export const DRAGON_ACHIEVEMENT_MOCK_DATA: DragonAchievement[] = [
  {
    id: 'achievement-first-flight',
    backendAchievementId: 'ach_first_flight',
    title: 'First Flight',
    description: 'Complete the first family quest and enter the shared chronicle.',
    category: 'quest',
    rarity: 'common',
    visibility: 'visible',
    icon: 'Flight',
    points: 10,
    xp: 120,
    progress: 1,
    progressMax: 1,
    completed: true,
    completedAt: '2025-01-12',
    requirements: [{ id: 'req-first-quest', label: 'Quest completed', target: 1, current: 1, backendField: 'quest.completed_count' }],
    rewards: [{ id: 'reward-first-flight-xp', type: 'xp', label: 'XP', value: 120, backendRewardId: 'reward_xp_120' }],
    seasonal: false,
    hiddenUntilUnlocked: false,
    repeatable: false,
    futureMetadata: { sourceModule: 'quest_board', backendFields: { questCount: 'quest.completed_count' } }
  },
  {
    id: 'achievement-flame-keeper',
    backendAchievementId: 'ach_flame_keeper',
    title: 'Flame Keeper',
    description: 'Maintain a seven day activity streak inside Dragon House.',
    category: 'activity',
    rarity: 'uncommon',
    visibility: 'visible',
    icon: 'Flame',
    points: 25,
    xp: 250,
    progress: 5,
    progressMax: 7,
    completed: false,
    completedAt: null,
    requirements: [{ id: 'req-activity-streak', label: 'Activity streak', target: 7, current: 5, backendField: 'activity.current_streak' }],
    rewards: [{ id: 'reward-flame-badge', type: 'badge', label: 'Flame Keeper badge', value: 'flame_keeper', backendRewardId: 'reward_badge_flame_keeper' }],
    seasonal: false,
    hiddenUntilUnlocked: false,
    repeatable: true,
    futureMetadata: { sourceModule: 'profile', backendFields: { streak: 'activity.current_streak' } }
  },
  {
    id: 'achievement-watchtower-guardian',
    backendAchievementId: 'ach_watchtower_guardian',
    title: 'Watchtower Guardian',
    description: 'Join ten Tower Defense sessions and guard the fortress line.',
    category: 'tower_defense',
    rarity: 'rare',
    visibility: 'visible',
    icon: 'Tower',
    points: 40,
    xp: 400,
    progress: 8,
    progressMax: 10,
    completed: false,
    completedAt: null,
    requirements: [{ id: 'req-tower-defense', label: 'Tower Defense sessions', target: 10, current: 8, backendField: 'tower_defense.participation_count' }],
    rewards: [{ id: 'reward-guardian-title', type: 'title', label: 'Guardian title', value: 'Guardian', backendRewardId: 'reward_title_guardian' }],
    seasonal: false,
    hiddenUntilUnlocked: false,
    repeatable: false,
    futureMetadata: { sourceModule: 'tower_defense' }
  },
  {
    id: 'achievement-council-voice',
    backendAchievementId: 'ach_council_voice',
    title: 'Council Voice',
    description: 'Attend five family meetings and shape the next command.',
    category: 'meeting',
    rarity: 'rare',
    visibility: 'visible',
    icon: 'Council',
    points: 45,
    xp: 450,
    progress: 5,
    progressMax: 5,
    completed: true,
    completedAt: '2025-03-08',
    requirements: [{ id: 'req-meeting-attendance', label: 'Meetings attended', target: 5, current: 5, backendField: 'calendar.meetings_attended' }],
    rewards: [{ id: 'reward-council-decoration', type: 'decoration', label: 'Council flame decoration', value: 'council_flame' }],
    seasonal: false,
    hiddenUntilUnlocked: false,
    repeatable: false,
    futureMetadata: { sourceModule: 'calendar' }
  },
  {
    id: 'achievement-ancient-one',
    backendAchievementId: 'ach_ancient_one',
    title: 'Ancient One',
    description: 'Remain active across a full year of Dragon House history.',
    category: 'attendance',
    rarity: 'epic',
    visibility: 'hidden',
    icon: 'Ancient',
    points: 80,
    xp: 900,
    progress: 213,
    progressMax: 365,
    completed: false,
    completedAt: null,
    requirements: [{ id: 'req-days-active', label: 'Days active', target: 365, current: 213, backendField: 'attendance.days_active' }],
    rewards: [{ id: 'reward-ancient-frame', type: 'profile_frame', label: 'Ancient profile frame', value: 'ancient_frame' }],
    seasonal: false,
    hiddenUntilUnlocked: true,
    repeatable: false,
    futureMetadata: { sourceModule: 'members' }
  },
  {
    id: 'achievement-founder',
    backendAchievementId: 'ach_founder',
    title: 'Founder',
    description: 'Stand among the original Dragon House founders.',
    category: 'founder',
    rarity: 'legendary',
    visibility: 'visible',
    icon: 'Crown',
    points: 150,
    xp: 1500,
    progress: 1,
    progressMax: 1,
    completed: true,
    completedAt: '2024-11-20',
    requirements: [{ id: 'req-founder-static', label: 'Founder registry', target: 1, current: 1, backendField: 'members.founder_flag' }],
    rewards: [
      { id: 'reward-founder-role', type: 'role_unlock', label: 'Founder role', value: 'founder', backendRewardId: 'reward_role_founder' },
      { id: 'reward-founder-artifact', type: 'artifact', label: 'Founding ember artifact', value: 'founding_ember' }
    ],
    seasonal: false,
    hiddenUntilUnlocked: false,
    repeatable: false,
    futureMetadata: { sourceModule: 'members' }
  },
  {
    id: 'achievement-eclipse-dragon',
    backendAchievementId: 'ach_eclipse_dragon',
    title: 'Eclipse Dragon',
    description: 'A mythic seal reserved for a future synchronized Discord ritual.',
    category: 'discord',
    rarity: 'mythic',
    visibility: 'secret',
    icon: 'Eclipse',
    points: 300,
    xp: 3000,
    progress: 0,
    progressMax: 1,
    completed: false,
    completedAt: null,
    requirements: [{ id: 'req-discord-sync', label: 'Discord ritual sync', target: 1, current: 0, backendField: 'discord.ritual_completed' }],
    rewards: [{ id: 'reward-eclipse-item', type: 'inventory_item', label: 'Eclipse relic', value: 'eclipse_relic' }],
    seasonal: false,
    hiddenUntilUnlocked: true,
    repeatable: false,
    futureMetadata: { sourceModule: 'discord', backendFields: { ritual: 'discord.ritual_completed' } }
  },
  {
    id: 'achievement-season-banner',
    backendAchievementId: 'ach_season_banner',
    title: 'Season Banner',
    description: 'Earn the current season reward before the banner fades.',
    category: 'seasonal',
    rarity: 'epic',
    visibility: 'visible',
    icon: 'Banner',
    points: 90,
    xp: 1000,
    progress: 60,
    progressMax: 100,
    completed: false,
    completedAt: null,
    requirements: [{ id: 'req-season-score', label: 'Season score', target: 100, current: 60, backendField: 'season.current_score' }],
    rewards: [{ id: 'reward-season-decoration', type: 'decoration', label: 'Season hall banner', value: 'season_hall_banner' }],
    seasonal: true,
    hiddenUntilUnlocked: false,
    repeatable: false,
    futureMetadata: { sourceModule: 'notifications', backendSeasonId: 'season_01', startsAt: '2025-01-01', endsAt: '2025-12-31' }
  }
];
