import type { DragonEvent } from './dragon-event-models';

export const DRAGON_EVENT_MOCK_DATA: DragonEvent[] = [
  {
    id: 'event-war-council-july',
    backendEventId: 'evt_war_council_2026_07_30',
    title: 'War Council',
    description: 'Council meeting for activity, roles and next week priorities.',
    type: 'family_meeting',
    category: 'meeting',
    status: 'scheduled',
    priority: 'critical',
    visibility: 'members',
    owner: { id: 'anastasia', name: 'Anastasia_Dragons', role: 'Owner' },
    creator: { id: 'anastasia', name: 'Anastasia_Dragons', role: 'Owner' },
    participants: [
      { id: 'anastasia', name: 'Anastasia_Dragons', role: 'Owner' },
      { id: 'guardians', name: 'Hall Guardians', role: 'Council' }
    ],
    participantCount: 2,
    maxParticipants: null,
    location: { label: 'War Council', kind: 'dragon_room', backendLocationId: 'room_war_council' },
    calendar: { enabled: true, stableEventKey: 'event:war-council:2026-07-30', colorKey: 'dragon_meeting' },
    startsAt: '2026-07-30T20:30:00+03:00',
    endsAt: '2026-07-30T21:30:00+03:00',
    allDay: false,
    timezone: 'Europe/Kiev',
    repeat: { frequency: 'none' },
    tags: ['council', 'planning'],
    rewards: [{ id: 'reward-war-council-xp', type: 'xp', label: 'Council XP', value: 50, backendRewardId: 'rew_council_xp' }],
    xp: 50,
    achievementIds: ['ach_flame_keeper'],
    questIds: [],
    notifications: { enabled: true, channels: ['hub', 'popup', 'discord'], reminders: [{ offsetMinutes: 60 }] },
    discord: { channelId: 'discord_council_channel', guildId: 'dragon_house' },
    createdAt: '2026-07-20T12:00:00+03:00',
    updatedAt: '2026-07-27T19:00:00+03:00',
    source: { sourceModule: 'events', sourceId: 'war-council-july', importedAt: '2026-07-20T12:00:00+03:00' },
    futureMetadata: { backendFields: { activity: 'lastActivity' }, achievementLinks: ['ach_flame_keeper'] }
  },
  {
    id: 'event-weekly-quests',
    backendEventId: 'evt_weekly_quests_2026_08_01',
    title: 'Weekly Family Quests',
    description: 'Prepare tasks, reports and rewards for Dragon House members.',
    type: 'quest',
    category: 'quest',
    status: 'scheduled',
    priority: 'normal',
    visibility: 'members',
    owner: { id: 'quest-forge', name: 'Quest Forge' },
    creator: { id: 'quest-forge', name: 'Quest Forge' },
    participants: [{ id: 'quest-team', name: 'Quest Team' }],
    participantCount: 1,
    maxParticipants: null,
    location: { label: 'Quest Forge', kind: 'dragon_room', backendLocationId: 'room_quest_forge' },
    calendar: { enabled: true, stableEventKey: 'event:weekly-quests:2026-08-01', colorKey: 'quest' },
    startsAt: '2026-08-01T19:00:00+03:00',
    endsAt: null,
    allDay: false,
    timezone: 'Europe/Kiev',
    repeat: { frequency: 'weekly', interval: 1, backendRuleId: 'repeat_weekly_quests' },
    tags: ['quests', 'rewards'],
    rewards: [{ id: 'reward-quest-board', type: 'achievement', label: 'Quest Board Link', value: 'ach_quest_keeper' }],
    xp: 35,
    achievementIds: ['ach_quest_keeper'],
    questIds: ['quest_weekly_family'],
    notifications: { enabled: true, channels: ['hub', 'popup'], reminders: [{ offsetMinutes: 120 }] },
    createdAt: '2026-07-22T10:00:00+03:00',
    updatedAt: '2026-07-22T10:00:00+03:00',
    source: { sourceModule: 'quest_board', sourceId: 'quest_weekly_family' },
    futureMetadata: { questLinks: ['quest_weekly_family'], achievementLinks: ['ach_quest_keeper'] }
  },
  {
    id: 'event-flame-ritual',
    backendEventId: 'evt_flame_ritual_2026_07_27',
    title: 'Flame Ritual',
    description: 'Ceremonial slot for an important family announcement.',
    type: 'announcement',
    category: 'announcement',
    status: 'completed',
    priority: 'high',
    visibility: 'members',
    owner: { id: 'dragon-house', name: 'Dragon House' },
    creator: { id: 'dragon-house', name: 'Dragon House' },
    participants: [{ id: 'family', name: 'Dragon House Family' }],
    participantCount: 1,
    location: { label: 'Hall of Flame', kind: 'dragon_room', backendLocationId: 'room_hall_of_flame' },
    calendar: { enabled: true, stableEventKey: 'event:flame-ritual:2026-07-27', colorKey: 'ritual' },
    startsAt: '2026-07-27T21:00:00+03:00',
    endsAt: null,
    allDay: false,
    timezone: 'Europe/Kiev',
    repeat: { frequency: 'none' },
    tags: ['ritual', 'announcement'],
    rewards: [],
    xp: 20,
    achievementIds: [],
    questIds: [],
    notifications: { enabled: false, channels: ['hub'], reminders: [] },
    createdAt: '2026-07-24T09:00:00+03:00',
    updatedAt: '2026-07-27T22:00:00+03:00',
    source: { sourceModule: 'manual', sourceId: 'ritual-flame' },
    futureMetadata: { completionMetadata: { completedBy: 'dragon-house' } }
  },
  {
    id: 'event-resource-audit',
    backendEventId: 'evt_resource_audit_2026_07_27',
    title: 'Resource Audit',
    description: 'Review materials, notes and the future Treasury structure.',
    type: 'resource_run',
    category: 'resource',
    status: 'completed',
    priority: 'normal',
    visibility: 'leadership',
    owner: { id: 'treasury', name: 'Treasury Keepers' },
    creator: { id: 'treasury', name: 'Treasury' },
    participants: [{ id: 'treasury', name: 'Treasury Keepers' }],
    participantCount: 1,
    location: { label: 'Treasury', kind: 'dragon_room', backendLocationId: 'room_treasury' },
    calendar: { enabled: true, stableEventKey: 'event:resource-audit:2026-07-27', colorKey: 'resource' },
    startsAt: '2026-07-27T18:00:00+03:00',
    endsAt: null,
    allDay: false,
    timezone: 'Europe/Kiev',
    repeat: { frequency: 'none' },
    tags: ['resources', 'treasury'],
    rewards: [{ id: 'reward-resource-artifact', type: 'artifact', label: 'Ledger Artifact Slot', value: 'artifact_ledger_placeholder' }],
    xp: 25,
    achievementIds: [],
    questIds: [],
    resources: { resourceId: 'treasury-ledger', resourceType: 'audit', backendResourceEventId: 'res_evt_audit' },
    notifications: { enabled: true, channels: ['hub'], reminders: [{ offsetMinutes: 30 }] },
    createdAt: '2026-07-23T11:00:00+03:00',
    updatedAt: '2026-07-27T19:00:00+03:00',
    source: { sourceModule: 'resources', sourceId: 'resource-audit' },
    futureMetadata: { backendFields: { resourceId: 'resourceId' } }
  },
  {
    id: 'event-personal-focus',
    backendEventId: 'evt_personal_focus_2026_07_28',
    title: 'Personal Focus',
    description: 'Private slot for personal Dragon House tasks.',
    type: 'custom',
    category: 'custom',
    status: 'active',
    priority: 'low',
    visibility: 'private',
    owner: { id: 'anastasia', name: 'Anastasia_Dragons' },
    creator: { id: 'anastasia', name: 'Anastasia_Dragons' },
    participants: [{ id: 'anastasia', name: 'Anastasia_Dragons' }],
    participantCount: 1,
    location: { label: 'Dragon Chamber', kind: 'dragon_room', backendLocationId: 'room_dragon_chamber' },
    calendar: { enabled: true, stableEventKey: 'event:personal-focus:2026-07-28', colorKey: 'personal' },
    startsAt: '2026-07-28T16:00:00+03:00',
    endsAt: null,
    allDay: false,
    timezone: 'Europe/Kiev',
    repeat: { frequency: 'none' },
    tags: ['focus'],
    rewards: [],
    xp: 10,
    achievementIds: [],
    questIds: [],
    notifications: { enabled: false, channels: ['hub'], reminders: [] },
    createdAt: '2026-07-26T13:00:00+03:00',
    updatedAt: '2026-07-28T16:00:00+03:00',
    source: { sourceModule: 'profile', sourceId: 'personal-focus' },
    futureMetadata: { extensionSlots: { profileDecoration: true } }
  },
  {
    id: 'event-defense-training',
    backendEventId: 'evt_defense_training_2026_08_06',
    title: 'Defense Training',
    description: 'Preparation for combat activity and role assignment.',
    type: 'tower_defense',
    category: 'defense',
    status: 'scheduled',
    priority: 'critical',
    visibility: 'members',
    owner: { id: 'war-council', name: 'War Council' },
    creator: { id: 'war-council', name: 'War Council' },
    participants: [
      { id: 'guardians', name: 'Hall Guardians' },
      { id: 'war-team', name: 'War Team' }
    ],
    participantCount: 2,
    location: { label: 'War Council', kind: 'dragon_room', backendLocationId: 'room_war_council' },
    calendar: { enabled: true, stableEventKey: 'event:defense-training:2026-08-06', colorKey: 'war_event' },
    startsAt: '2026-08-06T22:00:00+03:00',
    endsAt: null,
    allDay: false,
    timezone: 'Europe/Kiev',
    repeat: { frequency: 'none' },
    tags: ['tower-defense', 'training'],
    rewards: [{ id: 'reward-defense-xp', type: 'xp', label: 'Defense XP', value: 75, backendRewardId: 'rew_defense_xp' }],
    xp: 75,
    achievementIds: ['ach_guardian'],
    questIds: [],
    towerDefense: {
      defenseId: 'td_future_training',
      towerId: 'tower-training',
      towerName: 'Defense Training Tower',
      towerCode: 'TRN-01',
      commanderMemberId: 'war-council',
      readiness: 'ready',
      defenseStatus: 'scheduled',
      waveId: 'wave_placeholder',
      attendance: [{ memberId: 'guardians', status: 'present' }],
      result: 'scheduled',
      rewardId: 'reward-defense-xp'
    },
    notifications: { enabled: true, channels: ['hub', 'popup', 'discord'], reminders: [{ offsetMinutes: 180 }] },
    discord: { channelId: 'discord_war_channel', guildId: 'dragon_house' },
    createdAt: '2026-07-25T18:00:00+03:00',
    updatedAt: '2026-07-25T18:00:00+03:00',
    source: { sourceModule: 'tower_defense', sourceId: 'td_future_training' },
    futureMetadata: { achievementLinks: ['ach_guardian'], extensionSlots: { waveCount: 0 } }
  }
];
