import type { DragonTowerDefense } from './tower-defense-models';

export const DRAGON_TOWER_DEFENSE_MOCK_DATA: DragonTowerDefense[] = [
  {
    id: 'defense-vespucci-active',
    backendDefenseId: 'td_vespucci_2026_07_28',
    eventId: 'event-defense-vespucci-active',
    title: 'Захист вишки: Vespucci',
    description: 'Операція Вогняної варти біля західної вишки. Manual/mock availability for this phase.',
    tower: {
      towerId: 'tower-vespucci',
      towerName: 'Vespucci Signal Tower',
      towerCode: 'VSP-04',
      location: { label: 'Vespucci / western signal line', backendLocationId: 'tower_location_vespucci' },
      map: { x: 24.4, y: 71.8, zone: 'West Coast', backendMapId: 'map_tower_vespucci' },
      visual: { icon: 'Tower', markerColor: 'ember' }
    },
    status: 'gathering',
    priority: 'critical',
    scheduledAt: '2026-07-28T20:30:00+03:00',
    startsAt: '2026-07-28T21:00:00+03:00',
    endedAt: null,
    timezone: 'Europe/Kiev',
    allDay: false,
    wave: 2,
    phase: 'forming',
    commanderMemberId: 'anastasia',
    createdByMemberId: 'anastasia',
    minimumGuardCount: 3,
    recommendedGuardCount: 5,
    maximumGuardCount: 8,
    responses: [
      { memberId: 'anastasia', response: 'confirmed', respondedAt: '2026-07-28T19:45:00+03:00' },
      { memberId: 'guardians', response: 'joining', respondedAt: '2026-07-28T19:50:00+03:00' },
      { memberId: 'war-team', response: 'available', respondedAt: '2026-07-28T19:55:00+03:00' }
    ],
    attendance: [
      { memberId: 'anastasia', status: 'unconfirmed' },
      { memberId: 'guardians', status: 'unconfirmed' },
      { memberId: 'war-team', status: 'unconfirmed' }
    ],
    participantCount: 3,
    confirmedCount: 1,
    result: 'pending',
    score: null,
    contribution: { notes: 'Initial response is manual/mock until Discord sync exists.' },
    notes: 'Варта збирається біля вишки.',
    failureReason: null,
    completedByMemberId: null,
    completedAt: null,
    xp: 120,
    rewardIds: ['reward_fire_guard_xp'],
    achievementIds: ['ach_guardian'],
    leaderboardEligible: true,
    statisticsEligible: true,
    source: { sourceModule: 'tower_defense', sourceId: 'defense-vespucci-active', backendFields: { towerId: 'towerId' } },
    discord: { guildId: 'dragon_house', channelId: 'discord_war_channel', voiceChannelId: null, syncedAt: null },
    backendMetadata: { futureApiRoute: '/api/tower-defense' },
    createdAt: '2026-07-28T18:00:00+03:00',
    updatedAt: '2026-07-28T19:55:00+03:00'
  },
  {
    id: 'defense-sandy-upcoming',
    backendDefenseId: 'td_sandy_2026_07_29',
    eventId: 'event-defense-sandy-upcoming',
    title: 'Захист вишки: Sandy',
    description: 'Scheduled Fire Guard defense for the desert relay tower.',
    tower: {
      towerId: 'tower-sandy',
      towerName: 'Sandy Shores Relay',
      towerCode: 'SND-11',
      location: { label: 'Sandy Shores / north relay', backendLocationId: 'tower_location_sandy' },
      map: { x: 63.2, y: 41.1, zone: 'Desert', backendMapId: 'map_tower_sandy' },
      visual: { icon: 'Relay', markerColor: 'gold' }
    },
    status: 'scheduled',
    priority: 'high',
    scheduledAt: '2026-07-29T19:30:00+03:00',
    startsAt: '2026-07-29T20:00:00+03:00',
    endedAt: null,
    timezone: 'Europe/Kiev',
    allDay: false,
    wave: 1,
    phase: 'signal',
    commanderMemberId: 'guardians',
    createdByMemberId: 'anastasia',
    minimumGuardCount: 2,
    recommendedGuardCount: 4,
    maximumGuardCount: 6,
    responses: [{ memberId: 'guardians', response: 'confirmed', respondedAt: '2026-07-28T15:00:00+03:00' }],
    attendance: [{ memberId: 'guardians', status: 'unconfirmed' }],
    participantCount: 1,
    confirmedCount: 1,
    result: 'pending',
    score: null,
    notes: null,
    xp: 90,
    rewardIds: ['reward_fire_guard_xp'],
    achievementIds: ['ach_guardian'],
    leaderboardEligible: true,
    statisticsEligible: true,
    source: { sourceModule: 'tower_defense', sourceId: 'defense-sandy-upcoming' },
    discord: { guildId: 'dragon_house', channelId: 'discord_war_channel', syncedAt: null },
    backendMetadata: {},
    createdAt: '2026-07-28T13:00:00+03:00',
    updatedAt: '2026-07-28T15:00:00+03:00'
  },
  {
    id: 'defense-paleto-history',
    backendDefenseId: 'td_paleto_2026_07_24',
    eventId: 'event-defense-paleto-history',
    title: 'Захист вишки: Paleto',
    description: 'Completed operation recorded for Fire Guard history.',
    tower: {
      towerId: 'tower-paleto',
      towerName: 'Paleto Ridge Tower',
      towerCode: 'PLT-02',
      location: { label: 'Paleto Ridge', backendLocationId: 'tower_location_paleto' },
      map: { x: 42.7, y: 13.6, zone: 'North', backendMapId: 'map_tower_paleto' },
      visual: { icon: 'Ridge', markerColor: 'success' }
    },
    status: 'completed',
    priority: 'normal',
    scheduledAt: '2026-07-24T20:00:00+03:00',
    startsAt: '2026-07-24T20:15:00+03:00',
    endedAt: '2026-07-24T20:55:00+03:00',
    timezone: 'Europe/Kiev',
    allDay: false,
    wave: 3,
    phase: 'closed',
    commanderMemberId: 'anastasia',
    createdByMemberId: 'anastasia',
    minimumGuardCount: 3,
    recommendedGuardCount: 5,
    maximumGuardCount: 8,
    responses: [
      { memberId: 'anastasia', response: 'confirmed', respondedAt: '2026-07-24T18:30:00+03:00' },
      { memberId: 'guardians', response: 'confirmed', respondedAt: '2026-07-24T18:35:00+03:00' },
      { memberId: 'war-team', response: 'confirmed', respondedAt: '2026-07-24T18:40:00+03:00' }
    ],
    attendance: [
      { memberId: 'anastasia', status: 'present', confirmedByMemberId: 'anastasia', confirmedAt: '2026-07-24T20:58:00+03:00', contribution: { score: 45 } },
      { memberId: 'guardians', status: 'present', confirmedByMemberId: 'anastasia', confirmedAt: '2026-07-24T20:58:00+03:00', contribution: { score: 38 } },
      { memberId: 'war-team', status: 'late', confirmedByMemberId: 'anastasia', confirmedAt: '2026-07-24T20:58:00+03:00', contribution: { score: 22 } }
    ],
    participantCount: 3,
    confirmedCount: 3,
    result: 'defended',
    score: 105,
    contribution: { score: 105, notes: 'Stable defense with one late arrival.' },
    notes: 'Вишку захищено.',
    failureReason: null,
    completedByMemberId: 'anastasia',
    completedAt: '2026-07-24T20:58:00+03:00',
    xp: 150,
    rewardIds: ['reward_fire_guard_xp', 'reward_defense_history'],
    achievementIds: ['ach_guardian'],
    leaderboardEligible: true,
    statisticsEligible: true,
    source: { sourceModule: 'tower_defense', sourceId: 'defense-paleto-history' },
    discord: { guildId: 'dragon_house', channelId: 'discord_war_channel', syncedAt: null },
    backendMetadata: {},
    createdAt: '2026-07-24T17:30:00+03:00',
    updatedAt: '2026-07-24T20:58:00+03:00'
  }
];
